# Based on:
# https://glebbahmutov.com/blog/cypress-parallel-free-based-on-timings/
# https://glebbahmutov.com/blog/cypress-parallel-free/

name: Cypress tests
on: push
jobs:
    # example splitting all tests across GitHub machines
    prepare:
        runs-on: ubuntu-latest
        # explicitly set the output of this job
        # so that other jobs can use it
        outputs:
            matrix: ${{ steps.prepare.outputs.matrix }}
        steps:
            # generate the list using a bash script
            - name: Create matrix ⊹
              id: prepare
              # for reusable workflow, must use the full action reference
              uses: bahmutov/gh-build-matrix@main
              with:
                  n: 4 # number of containers to output

            # - name: Print result 🖨
            #   run: echo '${{ steps.prepare.outputs.matrix }}'

    test-split:
        needs: prepare
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
        steps:
            - name: Checkout 🛎
              uses: actions/checkout@v4

            # - name: Print GitHub variables 🖨
            #   run: npx @bahmutov/print-env GITHUB

            # - name: Print GitHub strategy context 🖨
            #   run: echo '${{ toJSON(strategy) }}'

            - name: Run split Cypress tests 🧪
              # https://github.com/cypress-io/github-action
              uses: cypress-io/github-action@v6
              with:
                  working-directory: ./dream-lab-frontend
                  start: npm start
                  wait-on: "http://localhost:5173" # Waits for above
                  publish-summary: false
              env:
                  SPLIT: ${{ strategy.job-total }}
                  SPLIT_INDEX: ${{ strategy.job-index }}
                  SPLIT_FILE: "timings.json"
                  DEBUG: cypress-split
                  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  CYPRESS_API_URL: ${{secrets.API_URL}}
                  VITE_API_URL: ${{ secrets.API_URL }}
